import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>wiwoproduction.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen px-16 flex flex-col justify-center items-center">
        <h1 className="text-7xl font-bold">Hello</h1>
        <p className="text-2xl my-16">I&apos;m Wojciech Więcławski</p>
      </main>

      <footer className="">Wiwo</footer>
    </div>
  );
}
